from flask import Flask, request, render_template
from os import listdir, sep
import json
from flask import jsonify

app = Flask(__name__)

'''a function to parse the data generated by the role_db_builder.sh file'''
def db_parser():
    role_dir = "./roles"

    roles = [] #empty list
    files = listdir(role_dir)

    id = 0
    for role_file in files:
        fd = open(role_dir + sep + role_file)
        #print(role_file)
        role = json.load(fd)
        role["id"] = id
        id = id +1
        roles.append(role)

    return roles

roles = db_parser()

app = Flask(__name__, )


@app.route("/roles", methods=["GET"])
def get_roles():
    if request.method == 'GET':
        #app.logger.info(roles)
        return jsonify(roles)

@app.route("/", methods=["GET"])
def index():
    if request.method == 'GET':
        return render_template('index.html')
