// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "dsdr/models"

	mock "github.com/stretchr/testify/mock"
)

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

// Connect provides a mock function with given fields: _a0
func (_m *DB) Connect(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Roles provides a mock function with given fields:
func (_m *DB) Roles() []models.BasicIAMRole {
	ret := _m.Called()

	var r0 []models.BasicIAMRole
	if rf, ok := ret.Get(0).(func() []models.BasicIAMRole); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BasicIAMRole)
		}
	}

	return r0
}
