name: Go Build

on:
  push:
    paths:
      - 'server/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'server/**'
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: cd ./server && go build -v .

    - name: Test
      run: cd ./server && go test -v -cover ./...
