name: Svelte Build

on:
  push:
    paths:
      - 'app/**'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'app/**'
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: cd ./app && npm install -g npm@7.24 && npm install && npm run build

    - name: Test
      run: cd ./app && npm install -g npm@7.24 && npm run test
